- README.md
> docs:添加开发状况展示

- Tools/自动化/连按/自动左键连点.py
- Tools/自动化/连按/自动按键连按.py
- 环境配置/库文件.py
ASK:
应该要把旧的输出统一为新风格吗？我担心以后可能会有其他风格，再进行统一会比较麻烦。
@Luna-Grace
> [style] 统一输出风格

- Tools/开发工具/git/账号切换.py
> [fix] 修复切换失败仍显示切换成功的问题

- Tools/去除代码注释/[实验性]remove_html_comments_noenter.py
- Tools/去除代码注释/remove_c_style_comments.py
- Tools/去除代码注释/remove_html_comments.py
- Tools/去除代码注释/remove_python_comments.py
> [style] 更正选取文件时的描述

- README.md
> 版本：v1.3.2
此PR应该在 microsoft/winget-pkgs#157822 关闭/合并后关闭/合并
> docs: 更新对于winget获取的方法

- Tools/开发工具/Script/ffdev.ps1
- Tools/开发工具/git/git连续尝试.py
> feat: 新增 开发工具/git连续尝试工具 

- README.md
Issue [文档] 是否应该填写所有关于winget的PR？ #75
@fjwxzde set
> docs: Update doc to add all winget PR.

- Tools/【实验性工具】/自动化/自动打包所有py文件/使用Nuitka.py
- Tools/【实验性工具】/自动化/自动打包所有py文件/使用Pyinstaller.py
@fjwxzde set 
@Luna-Grace 请帮忙测试下
> fix: 修复Issue #80 #79

- Tools/开发工具/git/git连续尝试.py
- Tools/开发工具/git/连续pull尝试.py
- Tools/开发工具/git/连续push尝试.py
Sync commit:
* pref: 在某个仓库中执行git相关自动化时可以省去选择仓库目录的步骤
* pref: 避免不必要的进程
* fix: 修复路径不是执行处的问题
> pref: 在某个仓库中执行git相关自动化时可以省去选择仓库目录的步骤 ( DuckDuckStudio/Fufu_Dev_Tools#6 )

- Tools/系统时间显示/time.pyw
> pref: 系统时间显示工具依据窗口拉大拉小而调整字体大小 (#86)

- Tools/开发工具/git/git连续尝试.py
- Tools/开发工具/git/连续pull尝试.py
- Tools/开发工具/git/连续push尝试.py
Fix DuckDuckStudio/Fufu_Dev_Tools#7
> pref: 让git相关连续尝试工具的通知显示具体仓库

- README.md
> docs: 更新winget支持版本

- Tools/开发工具/git/git连续尝试.py
- Tools/开发工具/git/账号切换.py
- Tools/开发工具/git/连续pull尝试.py
- Tools/开发工具/git/连续push尝试.py
- Tools/开发工具/总调用.py
- Tools/开发工具/目录复制.pyw
同步 DuckDuckStudio/Fufu_Dev_Tools#13 的修改。
覆盖同步
---
> pref: 退出代码与通知优化

- DEV-PACK.py
- Tools/开发工具/Script/ffdev.ps1
Version 2024.08.05.0100 → 2024.09.08.2000
---
> Auto Update FufuDevTools to 2024.09.08.2000

- Tools/【实验性工具】/自动化/自动打包所有py文件/使用Nuitka.py
- Tools/【实验性工具】/自动化/自动打包所有py文件/使用Pyinstaller.py
> pref: 为自动打包工具添加开始打包时的输出 (#109)

- .github/dependabot.yml
> deps: dependabot.yml

- Tools/【实验性工具】/自动化/自动打包所有py文件/使用Nuitka.py
- Tools/【实验性工具】/自动化/自动打包所有py文件/使用Pyinstaller.py
- Tools/删除/删除指定格式文件.py
- 芙芙工具箱.pyw
RE: 替换 `x = x+1` to `x += 1`
---
> [style]: 使用 `+=`

- Tools/【实验性工具】/自动化/自动打包所有py文件/使用Nuitka.py
- Tools/【实验性工具】/自动化/自动打包所有py文件/使用Pyinstaller.py
> fix: fix [BUG]: 自动打包py/pyw文件时日志文件路径最后必须带`/` #123

- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/preference_adjective.yml
> feat: ✨优化议题表单

- README.md
> docs:更新 winget 支持版本

- README.md
> docs: 添加对于功能介绍页面的链接

- Tools/开发工具/Script/ffdev.ps1
> Sync: 同步开发工具仓库的修改

- .github/workflows/Notify-license-update.yml
> feat: 通知相关仓库更新许可文件工作流

- .github/dependabot.yml
> fix(deps): 修正 dependabot.yml 配置

- .github/CODEOWNERS
- .github/workflows/Pack_Release.yml
- DEV-PACK.py
- README.md
> develop(docs&fix): 文档更新与使用 UPX 压缩发行文件

- .github/workflows/Pack_Release.yml
> [!NOTE]
> 由于我们的修改版本号脚本不允许版本号以`v`开头，在发布tag时也不能以`v`开头
---
> feat(build): 自动将构建文件推送至发行版

- src/Tools/【实验性工具】/自动化/自动打包所有py文件/使用Nuitka.py
- src/Tools/休息一下/自启动设置（For-打包版）.py
- src/Tools/随机展示/main.pyw
- src/temporarily/config-save.py
- Fix https://github.com/DuckDuckStudio/Fufu_Tools/issues/46 还在追我！
---
> fix: 修复打包后的路径问题

- .github/workflows/Pack_Release.yml
- .gitignore
- 自动化脚本/清理待发布标签.py
> feat: 自动清理待发布标签

- src/Tools/随机展示/main.pyw
> fix: 在随机过程中禁止用户再次开始随机

- .github/workflows/Pack_Release.yml
> feat: 分别上传各个构建结果

- DEV-PACK.py
- src/Tools/【实验性工具】/自动化/自动打包所有py文件/使用Nuitka.py
- src/Tools/【实验性工具】/自动化/自动打包所有py文件/使用Pyinstaller.py
fix: 如果指定的日志存储文件夹或图标文件不存在，则执行无日志/图标打包
style: 将 \\ 替换为 os.sep 以改善兼容性
fix: 更正通知标题中的工具名称
---
> pref: 优化批量打包py/pyw文件工具

- src/Tools/系统时间显示/time.pyw
> feat(time): 深浅颜色主题切换

- .github/workflows/Pack_Release.yml
> ci: 将 Windows Runner 钉在 windows-2022
